language: rust
jobs:
  include:
    - stage: build
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install musl-tools
      script:
        - rustup target add x86_64-unknown-linux-musl
        - cargo build --target x86_64-unknown-linux-musl --release
        - strip target/x86_64-unknown-linux-musl/release/dilbert-feed
        - mkdir target/work
        - cp -t target/work LICENSE README.md target/x86_64-unknown-linux-musl/release/dilbert-feed
        - tar -czvf dilbert-feed-"${TRAVIS_TAG:-untagged}".tar.gz -C target/work .
      deploy:
        provider: releases
        token: $GITHUB_OAUTH_TOKEN
        file: dilbert-feed-*.tar.gz
        edge: true
        on:
          tags: true
