image: ekidd/rust-musl-builder:nightly

pipelines:
  default:
    - step:
        script:
          - sudo apt-get update && sudo apt-get install -y upx-ucl
          - cargo build --release
          - upx target/x86_64-unknown-linux-musl/release/dilbert-feed
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/x86_64-unknown-linux-musl/release/dilbert-feed"

