[package]
authors = ["Samuel Laurén <samuel.lauren@iki.fi>"]
description = "Generate Dilbert Atom feed with images."
license = "MIT"
name = "dilbert-feed"
publish = false
repository = "https://bitbucket.org/Soft/dilbert-feed"
version = "0.1.0"

[dependencies]
atom_syndication = "0.5.7"
failure = "0.1.1"
htmlescape = "0.3.1"
rayon = "0.9.0"
reqwest = "0.8.4"
select = "0.4.2"
structopt = "0.1.7"
structopt-derive = "0.1.6"
