[package]
authors = ["Samuel Laurén <samuel.lauren@iki.fi>"]
name = "dilbert-feed"
description = "Generate Dilbert Atom feed with images."
repository = "https://bitbucket.org/Soft/dilbert-feed"
version = "0.1.0"
license = "MIT"
publish = false

[dependencies]
atom_syndication = "0.5.7"
failure = "0.1.1"
reqwest = "0.8.4"
select = "0.4.2"
structopt = "0.1.7"
structopt-derive = "0.1.6"
